language: python

python:
  - "3.6.6"
  # - "2.6"
  # - "2.7"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.5"
  # - "3.6"
  # - "3.6"
  # - "3.7"


#Install all dependecies
install:
  - pip install -r requirements.txt
  - pip install coveralls

#Run tests
script:
  - python test.py
  -coverage run --source=home run.py test home

  after_success: coveralls
